//  Foursquare API keys
export const FS_CLIENT_ID = 'XC45SLP2PETGKNWV1UFQXSUJ0PNKIUVDQTX0IXOO3CFBGPSM';
export const FS_CLIENT_SECRET = '2TEPUANLKA4DIESECEK5T04GEDK31GID1IWJQ314O50VUOMU';

//   Google Maps API key
export const GOOGLE_MAP_KEY = 'AIzaSyASTD9r6pWJjIKgNUaQ46sWcMnkF2Nh-T4';
